### PR TITLE
Downgrading to babel v5.8.35 to fix the performance issues

### PR DESCRIPTION
**Pull request by senthilp**

### CODE REVIEW

**Comment by patrick-steele-idem** [comment]
@senthilp Did you investigate the slowness of babel v6? After doing a little research it seems that the issue might be resolved with npm 3 (oddly enough): https://phabricator.babeljs.io/T3067

If that is the case, then I would say that we should stick with babel v6

**Comment by senthilp** [comment]
From what I investigated, even with npm 3 it is still as not good as V5. I also read that the next (or a soon upcoming) minor version of babel will address some of the concerns. Having said that i am not sure when the core teams like VI & SRP will move to npm@4. Raja suggested keeping those domains in the current version at least for the next few months. So until we migrate we should use babel 5.x. Also updating to v6 is simple we can do it anytime.

**Comment by senthilp** [comment]
@patrick-steele-idem did you give though on this? I think until major of our projects are migrated to npm@4 we should be doing babel v5.

**Comment by patrick-steele-idem** [comment]
Hey @senthilp, I have concerns about downgrading to babel v5. babel v6 more closely follows the ES2015 spec and there is the potential of breaking existing code if we downgrade now and later switch from babel v5 to babel v6.

Also, any developer can choose to upgrade to whatever version of `npm` that they prefer:

```
npm install npm@^3 --global
```

I'm not aware of any compatibility problems associated with using the latest version of `npm`.

Another option is to let the application choose which version of babel to install and update lasso to work with whichever version that it finds installed. That might be the better way to go and it gives more flexibility.

**Comment by senthilp** [comment]
Agree that developers can upgrade to npm@3, but platform has recommended against it for certain projects. They also want to start on ES6 and this slowness would not be acceptable.

The option of application choosing babel version is good, but it will not be as seamless as what we have currently. Initially babel v5 should be sufficient as we will not be rolling to production right away.

Lets discuss this a little more in Slack and other forums to make a call.

**Comment by patrick-steele-idem** [comment]
Closing this old PR. Feel free to post comments here.

**Pull request closed without merging**
